### ISSUE TITLE
Fix Text Parsing

### ISSUE THREAD

**Issue by MicheleTobias** [MicheleTobias/LiteratureMapper#19]
It appears to be having an issue with the portion of the code that parses the json file the Zotero API sends back.

```
2018-11-08T13:59:47     WARNING    Traceback (most recent call last):
              File "C:/Users/mmtobias/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiteratureMapper\literature_mapper.py", line 369, in run
              data_parsed = parse_zotero(data)
              File "C:/Users/mmtobias/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LiteratureMapper\literature_mapper.py", line 347, in parse_zotero
              encoded_data = json.dumps(data.content)
              File "C:\OSGEO4~1\apps\Python37\lib\json\__init__.py", line 231, in dumps
              return _default_encoder.encode(obj)
              File "C:\OSGEO4~1\apps\Python37\lib\json\encoder.py", line 199, in encode
              chunks = self.iterencode(o, _one_shot=True)
              File "C:\OSGEO4~1\apps\Python37\lib\json\encoder.py", line 257, in iterencode
              return _iterencode(o, 0)
              File "C:\OSGEO4~1\apps\Python37\lib\json\encoder.py", line 179, in default
              raise TypeError(f'Object of type {o.__class__.__name__} '
             TypeError: Object of type bytes is not JSON serializable
```

**Comment by MicheleTobias** [comment]
Solved. We were processing the json more than it needed to be.
