### ISSUE TITLE
Support for Group Libraries

### ISSUE THREAD

**Issue by wildintellect** [MicheleTobias/LiteratureMapper#36]
The API request for a group library appears to succeed(maybe not), but the json returned might not be exactly the same as direct user collections. Was working on this in order to created a shared library for testing against.

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
Traceback (most recent call last):
  File "/home/vulpes/.qgis3/profiles/developer/python/plugins/LiteratureMapper/literature_mapper.py", line 409, in run
    data_parsed = parse_zotero(data)
  File "/home/vulpes/.qgis3/profiles/developer/python/plugins/LiteratureMapper/literature_mapper.py", line 382, in parse_zotero
    parsed_data = json.loads(zotero_response.content.decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wildintellect** [comment]
Ah group urls are different, ```/groups/<groupID>```, so user/group should be a drop down that alters the url pattern.

**Comment by MicheleTobias** [comment]
That makes sense.  I think potentially there could be some reorganization in the code that might help make implementing this fix a little easier (the code currently calls the API twice - once to make the table and another time to get the data before saving).
